07 generalizations and lambda expressions develop
StasLina/PRGR pull request #11
Opened 2024-04-01 14:48 UTC by StasLina

2024-04-02 07:45 UTC, KitovDanil requested changes

2024-04-02 07:45 UTC, KitovDanil commented on ConsoleApp1/Program.cs
> +        CustomTree<T> next(CustomTree<T> currentNode)
Идентификаторы методов используют PascalCase.

2024-04-02 07:45 UTC, KitovDanil commented on ConsoleApp1/Program.cs
> +        CustomTree<T> previous(CustomTree<T> currentNode)
Идентификаторы методов используют PascalCase.

2024-04-02 07:45 UTC, KitovDanil commented on ConsoleApp1/Program.cs
> +
Лишняя пустая строка

2024-04-02 07:45 UTC, KitovDanil commented on ConsoleApp1/Program.cs
> +
Лишняя пустая строка

2024-04-02 07:45 UTC, KitovDanil commented on ConsoleApp1/Program.cs
> +        }
Между разными методами следует вставлять пустую строку.

2024-04-02 07:45 UTC, KitovDanil commented on ConsoleApp1/Program.cs
> +        }
Между разными методами следует вставлять пустую строку.

2024-04-02 07:45 UTC, KitovDanil commented on ConsoleApp1/Program.cs
> +        }
Между разными методами следует вставлять пустую строку.

2024-04-02 07:45 UTC, KitovDanil commented on ConsoleApp1/Program.cs
> +    }
Между разными методами следует вставлять пустую строку.

2024-04-02 07:45 UTC, KitovDanil commented on ConsoleApp1/Program.cs
> +    }
Между разными методами следует вставлять пустую строку.

2024-04-02 07:45 UTC, KitovDanil commented on ConsoleApp1/Program.cs
> +    }
Между разными методами следует вставлять пустую строку.

2024-04-02 07:45 UTC, KitovDanil commented on ConsoleApp1/Program.cs
> +    CustomTree<T> leftNode = null, rightNode = null;
Если ты вставляешь строку между свойствами LeftNode и RightNode, то имеет смысл также отделить пустой строкой объявление полей от свойства LeftNode.

2024-04-02 07:45 UTC, KitovDanil commented on ConsoleApp1/Program.cs
> +"1) Очистить дерево\n2) Добавить значение\n3) Вывести по возрастанию\n4) Вывод по убыванию\n5) Вывод с использованием лямбда выражения";
При таком переносе текста на новую строку следует делать отступ в 4 пробела от уровня предыдущей строки.

2024-04-02 07:45 UTC, KitovDanil commented on ConsoleApp1/Program.cs
> +
Лишняя пустая строка

2024-04-02 07:45 UTC, KitovDanil commented on ConsoleApp1/Program.cs
> +
Лишняя пустая строка

2024-04-02 07:45 UTC, KitovDanil commented on ConsoleApp1/Program.cs
> +    }
Между разными методами следует вставлять пустую строку (требование Леонида Николаевича).

2024-04-02 07:45 UTC, KitovDanil commented on ConsoleApp1/Program.cs
> +    static CustomTree<double> customTree;
Идентификаторы статических полей именуются следующим образом: s_customTree

2024-04-02 07:45 UTC, KitovDanil commented on ConsoleApp1/Program.cs
> +    CustomTree<T> parentNode = null;
Идентификаторы private полей именуются следующим образом: _parentNode

2024-04-02 07:45 UTC, KitovDanil commented on ConsoleApp1/Program.cs
> +    T currentValue;
Идентификаторы private полей именуются следующим образом: _parentNode

2024-04-02 07:45 UTC, KitovDanil commented on ConsoleApp1/Program.cs
> +        CustomTree<T> value;
Идентификаторы private полей именуются следующим образом: _parentNode

2024-04-02 07:45 UTC, KitovDanil commented on ConsoleApp1/Program.cs
> +                //Если текущая является левой веткой
Между знаком комментария // и началом текста комментария ставится пробел

2024-04-02 07:45 UTC, KitovDanil commented on ConsoleApp1/Program.cs
> +                //Если текущая является левой веткой
Между знаком комментария // и началом текста комментария ставится пробел

2024-04-02 07:45 UTC, KitovDanil commented on ConsoleApp1/Program.cs
> +                    //Right node
Между знаком комментария // и началом текста комментария ставится пробел

2024-04-02 07:45 UTC, KitovDanil commented on ConsoleApp1/Program.cs
> +                //Дошли до вершины
Между знаком комментария // и началом текста комментария ставится пробел

2024-04-02 07:45 UTC, KitovDanil commented on ConsoleApp1/Program.cs
> +                    //leftNode
Между знаком комментария // и началом текста комментария ставится пробел

2024-04-02 07:45 UTC, KitovDanil commented on ConsoleApp1/Program.cs
> +                //Отправляем в левую ноду
Между знаком комментария // и началом текста комментария ставится пробел (могу дать ссылку на MSDN, где это прописано)

2024-04-02 07:45 UTC, KitovDanil commented on ConsoleApp1/Program.cs
> +                //Отправляем в правую ноду
Между знаком комментария // и началом текста комментария ставится пробел

2024-04-02 07:45 UTC, KitovDanil commented on ConsoleApp1/Program.cs
> +    }
Между разными методами следует вставлять пустую строку.

2024-04-02 07:45 UTC, KitovDanil commented on ConsoleApp1/Program.cs
> +        Func<CustomTree<double>, IEnumerable<double>> myFunc = val =>
val - плохое название переменной, особенно учитывая, что потом  идёт ещё и перебор по какому-то методу val

2024-04-02 07:45 UTC, KitovDanil commented on ConsoleApp1/Program.cs
> +        public static Iterator operator --(Iterator iter)
В каких-то местах программы переменные-итераторы называются it, в каких-то iter. Предлагаю привести к единому виду.

2024-04-02 12:20 UTC, StasLina commented on ConsoleApp1/Program.cs
> +        }
![image](https://github.com/StasLina/PRGR/assets/62825238/21a11a18-09ba-436a-bd6d-e3c7159f39d8)

ChatGpt пояснил данный момент, и я с ним соглашусь, отделять есть смысл большие участки кода.

2024-04-02 12:20 UTC, StasLina commented on ConsoleApp1/Program.cs
> +
V

2024-04-02 12:20 UTC, StasLina commented on ConsoleApp1/Program.cs
> +        CustomTree<T> previous(CustomTree<T> currentNode)
V

2024-04-02 12:20 UTC, StasLina commented on ConsoleApp1/Program.cs
> +        CustomTree<T> next(CustomTree<T> currentNode)
V

2024-04-02 12:20 UTC, StasLina commented on ConsoleApp1/Program.cs
> +                //Отправляем в правую ноду
V

2024-04-02 12:21 UTC, StasLina commented on ConsoleApp1/Program.cs
> +        Func<CustomTree<double>, IEnumerable<double>> myFunc = val =>
V

2024-04-02 12:21 UTC, StasLina commented on ConsoleApp1/Program.cs
> +        public static Iterator operator --(Iterator iter)
V

2024-04-02 13:11 UTC, KitovDanil requested changes

2024-04-02 13:11 UTC, KitovDanil commented on ConsoleApp1/Program.cs
> +            get { return isEndNext; }
В данном случае инлайн как раз-таки не стоит делать

2024-04-02 13:11 UTC, KitovDanil commented on ConsoleApp1/Program.cs
> +            }
Зачем скобки были так перенесены? Блок же пустой.

2024-04-02 13:11 UTC, KitovDanil commented on ConsoleApp1/Program.cs
> +        public Iterator(CustomTree<T> beginValue) { value = beginValue; }
Здесь тоже не стоит делать инлайн

2024-04-02 13:11 UTC, KitovDanil commented on ConsoleApp1/Program.cs
> +                        == currentNode.parentNode.leftNode.GetHashCode()))
Если один раз строка была перенесена, то при следующих переносах уже не нужно делать отступы

2024-04-04 06:29 UTC, StasLina commented on ConsoleApp1/Program.cs
> +        public Iterator(CustomTree<T> beginValue) { value = beginValue; }
V

2024-04-04 06:29 UTC, StasLina commented on ConsoleApp1/Program.cs
> +                        == currentNode.parentNode.leftNode.GetHashCode()))
V

2024-04-05 00:22 UTC, StasLina commented on ConsoleApp1/Program.cs
> +            }
V

2024-04-05 00:22 UTC, StasLina commented on ConsoleApp1/Program.cs
> +            get { return isEndNext; }
V

2024-04-05 00:23 UTC, StasLina commented on ConsoleApp1/Program.cs
> +                //Отправляем в левую ноду
V

2024-04-05 07:45 UTC, KitovDanil requested changes

2024-04-05 07:45 UTC, KitovDanil commented on ConsoleApp1/Program.cs
> +        public Iterator(CustomTree<T> beginValue) {
Фигурная скобка переносится на следующую строку

2024-04-05 11:17 UTC, StasLina commented on ConsoleApp1/Program.cs
> +        public Iterator(CustomTree<T> beginValue) {
V

2024-04-05 13:32 UTC, merged