8 windows forms development
StasLina/PRGR pull request #14
Opened 2024-04-18 05:09 UTC by StasLina

2024-04-18 06:26 UTC, KitovDanil requested changes
Программа также не синхронизирует дочерние директории

2024-04-18 06:26 UTC, KitovDanil commented on WindowsFormsApp1/Controller.cs
> +            Dictionary<string, TypeColor> PathMapColor = new Dictionary<string, TypeColor>();
Локальные переменные используют lowerCamelCase

2024-04-18 06:26 UTC, KitovDanil commented on WindowsFormsApp1/Model.cs
> +            }catch (Exception ex)
Нужен перенос на следующую строку

2024-04-18 06:26 UTC, KitovDanil commented on WindowsFormsApp1/Model.cs
> +        //Присуще системе MVC
Пропущен пробел после //

2024-04-18 06:26 UTC, KitovDanil commented on WindowsFormsApp1/Model.cs
> +                // Присуще системе MVC если биндить напряму в View
Напрямую

2024-04-18 06:26 UTC, KitovDanil commented on WindowsFormsApp1/Controller.cs
> +        // Определение контсрукторов
1) Конструкторов
2) Ниже не конструктор, а свойство

2024-04-18 06:26 UTC, KitovDanil commented on WindowsFormsApp1/Controller.cs
> +        Model model = null;
Рекомендовано: private Model _model = null;

2024-04-18 06:26 UTC, KitovDanil commented on WindowsFormsApp1/Controller.cs
> +            otherModel.DetermineDifferncesFiles(this.model, out filesToChange, out filesToRemove, out filesToCreate);
Леонид Николаевич забанил out

2024-04-18 06:26 UTC, KitovDanil commented on WindowsFormsApp1/Controller.cs
> +            foreach (ListViewItem item in view.ListItems.Items)
Имя item не конкретизирует, что содержится в переменной

2024-04-18 06:39 UTC, StasLina commented on WindowsFormsApp1/Controller.cs
> +            Dictionary<string, TypeColor> PathMapColor = new Dictionary<string, TypeColor>();
V

2024-04-18 06:39 UTC, StasLina commented on WindowsFormsApp1/Model.cs
> +            }catch (Exception ex)
V

2024-04-18 06:40 UTC, StasLina commented on WindowsFormsApp1/Model.cs
> +                // Присуще системе MVC если биндить напряму в View
ещё запятая нужна.

2024-04-18 06:42 UTC, StasLina commented on WindowsFormsApp1/Controller.cs
> +        // Определение контсрукторов
V

2024-04-18 06:45 UTC, StasLina commented on WindowsFormsApp1/Controller.cs
> +        Model model = null;
V

2024-04-18 06:45 UTC, StasLina commented on WindowsFormsApp1/Controller.cs
> +            foreach (ListViewItem item in view.ListItems.Items)
А тип переменной на что?

2024-04-18 06:48 UTC, StasLina commented on WindowsFormsApp1/Controller.cs
> +            foreach (ListViewItem item in view.ListItems.Items)
V

2024-04-18 06:48 UTC, StasLina commented on WindowsFormsApp1/Model.cs
> +        //Присуще системе MVC
V

2024-04-18 07:14 UTC, StasLina commented on WindowsFormsApp1/Controller.cs
> +            otherModel.DetermineDifferncesFiles(this.model, out filesToChange, out filesToRemove, out filesToCreate);
Вредина.

2024-04-18 07:15 UTC, StasLina commented
Поправил сделал синхронизацию файлов и подпапок.

2024-04-19 06:14 UTC, KitovDanil requested changes
Присутствуют минорные стилистические проблемы

2024-04-19 06:14 UTC, KitovDanil commented on WindowsFormsApp1/Controller.cs
> +            _view.ListItems.AutoResizeColumn(0,ColumnHeaderAutoResizeStyle.ColumnContent);
Пропущен пробел между фактическими параметрами

2024-04-19 06:14 UTC, KitovDanil commented on WindowsFormsApp1/Controller.cs
> +            var arrNames = _model.GetRelativeFiles();
Не рекомендовано использование var, если неочевидно, какой тип у переменной.
![image](https://github.com/StasLina/PRGR/assets/8685613/d6230b32-7741-44ab-9394-874486c640a7)

2024-04-19 06:14 UTC, KitovDanil commented on WindowsFormsApp1/Model.cs
> +        private string pathToDirectory;
Рекомендовано: private string pathToDirectory;
Если ты делаешь так в классе Controller, то логично по аналогии сделать и здесь.

2024-04-19 06:14 UTC, KitovDanil commented on WindowsFormsApp1/Model.cs
> +        List<PathChanged> PathChangeds = new List<PathChanged>();
1) Это private переменная, она не использует PascalCase.
2) "Changeds" вряд ли грамотно в рамках английского языка, предлагаю подобрать более удачный идентификатор, например, _pathChangedList

2024-04-19 06:14 UTC, KitovDanil commented on WindowsFormsApp1/Model.cs
> +        int  LoadFilesFromDirectory()
Лишний пробел между типом и идентификатором

2024-04-19 06:14 UTC, KitovDanil commented on WindowsFormsApp1/View.cs
> +        bool isIgnoreNextChangeText = false;
Здесь тоже private переменные, для определения которых рекомендован другой стиль

2024-04-20 02:38 UTC, StasLina commented on WindowsFormsApp1/Controller.cs
> +            _view.ListItems.AutoResizeColumn(0,ColumnHeaderAutoResizeStyle.ColumnContent);
V

2024-04-20 02:38 UTC, StasLina commented on WindowsFormsApp1/Controller.cs
> +            var arrNames = _model.GetRelativeFiles();
V

2024-04-20 02:40 UTC, StasLina commented on WindowsFormsApp1/Model.cs
> +        private string pathToDirectory;
Не понял суть проблемы?

2024-04-20 02:43 UTC, StasLina commented on WindowsFormsApp1/View.cs
> +        bool isIgnoreNextChangeText = false;
Эта переменная вообще не используемая)

2024-04-20 13:31 UTC, merged