04 io std develop
StasLina/PRGR pull request #5
Opened 2024-02-27 05:17 UTC by StasLina

На проверку

2024-02-27 05:45 UTC, KitovDanil requested changes

2024-02-27 05:45 UTC, KitovDanil commented on ConsoleApp4/Program.cs
> +        using (FileStream CurrentFileStream = new FileStream(filePath, FileMode.Create)) {
Рекомендовано:
`FileStream currentFileStream = new FileStream(filePath, FileMode.Create)`
https://learn.microsoft.com/ru-ru/dotnet/csharp/fundamentals/coding-style/coding-conventions
![image](https://github.com/StasLina/PRGR/assets/8685613/e447bff0-7575-404e-9343-f41317abc82c)

2024-02-27 05:45 UTC, KitovDanil commented on ConsoleApp4/Program.cs
> +        using (FileStream fs = new FileStream(filePath, FileMode.Open)) {
Из контекста, конечно, понятно, что fs - это FileStream, однако желательно писать единообразный код: выше в методе SerializeBinary() переменная называлась currentFileStream, значит и здесь стоит дать аналогичное название.

2024-02-27 05:45 UTC, KitovDanil commented on ConsoleApp4/Program.cs
> +        private int CurrElementIndex = 0, CountElements, ElementIndexCategory = 0;
Рекомендовано: currentElementIndex, countElements, elementIndexCategory.
https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/identifier-names
![image](https://github.com/StasLina/PRGR/assets/8685613/ac26aa65-4ab3-4a50-a094-edb565758ddb)

2024-02-27 05:45 UTC, KitovDanil commented on ConsoleApp4/Program.cs
> +public class TextFileContent {
Проблема по всему коду: открывающая фигурная скобка должна находиться на своей собственной линии.
https://learn.microsoft.com/ru-ru/dotnet/csharp/fundamentals/coding-style/coding-conventions
![image](https://github.com/StasLina/PRGR/assets/8685613/a21b8eb8-dc28-4672-b483-b715df1a4275)
https://ru.wikipedia.org/wiki/%D0%9E%D1%82%D1%81%D1%82%D1%83%D0%BF_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%A1%D1%82%D0%B8%D0%BB%D1%8C_%D0%9E%D0%BB%D0%BC%D0%B0%D0%BD%D0%B0

2024-02-27 06:08 UTC, StasLina commented on ConsoleApp4/Program.cs
> +public class TextFileContent {
Учтено.

2024-02-27 06:08 UTC, StasLina commented on ConsoleApp4/Program.cs
> +        private int CurrElementIndex = 0, CountElements, ElementIndexCategory = 0;
Учтено.

2024-02-27 06:08 UTC, StasLina commented on ConsoleApp4/Program.cs
> +        using (FileStream fs = new FileStream(filePath, FileMode.Open)) {
Исправил.

2024-02-27 06:08 UTC, StasLina commented on ConsoleApp4/Program.cs
> +        using (FileStream CurrentFileStream = new FileStream(filePath, FileMode.Create)) {
Исправил.

2024-02-27 06:10 UTC, KitovDanil requested changes

2024-02-27 06:10 UTC, KitovDanil commented on ConsoleApp4/Program.cs
> +        public class SmartDictinary {
Может, SmartDictionary? Здесь и везде в коде как будто буквы "o" не хватает.

2024-02-27 06:15 UTC, KitovDanil requested changes

2024-02-27 06:15 UTC, KitovDanil commented on ConsoleApp4/Program.cs
> +        public class SmartDictinary
Может, SmartDictionary? Здесь и везде в коде как будто "o" пропущена.

2024-02-27 06:18 UTC, KitovDanil commented on ConsoleApp4/Program.cs
> +        private int CurrElementIndex = 0, CountElements, ElementIndexCategory = 0;
ElementIndexCategory всё еще не исправлено.

2024-02-27 14:25 UTC, KitovDanil requested changes

2024-02-27 14:25 UTC, KitovDanil commented on ConsoleApp4/Program.cs
> +    public string fileName { get; set; }
Здесь обратная история: для public полей и свойств рекомендован PascalCase. Предыдущий мой комментарий на эту тему относился к неправильному именованию именно private полей.
https://learn.microsoft.com/ru-ru/dotnet/csharp/fundamentals/coding-style/identifier-names
![image](https://github.com/StasLina/PRGR/assets/8685613/03fd1f54-9eeb-499d-a9ec-427ba518c6a0)

Такая проблема встречается не раз в коде.

2024-02-27 14:25 UTC, KitovDanil commented on ConsoleApp4/Program.cs
> +        Dictionary<int, string> curKeywords = new Dictionary<int, string>();
Здесь current сокращается до cur, двумя строчками выше он же сокращается до curr, еще выше он не сокращается вовсе. Я предлагаю выбрать какой-то один вариант и везде называть переменные единообразно.

2024-02-27 14:25 UTC, KitovDanil commented on ConsoleApp4/Program.cs
> +            return;
return здесь не нужна. Может, оно для чего-то написано, но мне непонятно для чего.

2024-02-27 14:25 UTC, KitovDanil commented on ConsoleApp4/Program.cs
> +        Dictionary<int, TextFile> listFiles = new Dictionary<int, TextFile>();
Переменная listFiles объявлена, но не используется.

2024-02-27 14:25 UTC, KitovDanil commented on ConsoleApp4/Program.cs
> +            backupContent = new TextFileMemento(this.fileContent);
Здесь и в ряде функций ниже this не обязателен. В принципе это может быть так написано для читабельности, хочу пояснение по этому моменту.

2024-02-27 14:25 UTC, KitovDanil commented on ConsoleApp4/Program.cs
> +            this.fileContentInstance.SerializeBinary(fileName);
В функцию SerializeBinary() (и в ряд функций ниже) передается аргумент fileName, а принимают они аргумент filePath. Пользователь, вводя в приложении имя для нового файла, не подозревает, что на самом деле вводит путь.

Как я написал в ВК, BinaryFormatter, видимо, устарел, вместо него, судя по всему, используются BinaryReader и BinaryWriter. В то же время XMLSerializer работает нормально, и в твоей программе у меня получилось сериализовать файл, однако, как я и написал выше, пришлось передать ему не просто имя, а полный путь до файла (он не обязательно должен существовать, программа сама создает его, если он отсутствует).

2024-02-27 14:25 UTC, KitovDanil commented on ConsoleApp4/Program.cs
> +            this.fileContentInstance.SerializeBinary(fileName);
Также функция бросает исключения по типу того, что нет доступа к указанному файлу. Их стоит обработать.

2024-02-27 14:25 UTC, KitovDanil commented on ConsoleApp4/Program.cs
> +            Console.WriteLine("Введите имя для нового файа, который будет бинарно серелизован");
Опечатка: "файа". Ниже тоже надо исправить.

2024-02-27 14:25 UTC, KitovDanil commented on ConsoleApp4/Program.cs
> +using System.Diagnostics;
VisualStudio пишет, что 8 из 11 библиотек не нужны. Используются только 3: System.Xml.Serialization, System.Runtime.Serialization.Formatters.Binary, System.Diagnostics. Может, отключить остальные?

2024-02-27 14:25 UTC, KitovDanil commented on ConsoleApp4/Program.cs
> +#pragma warning disable SYSLIB0011
В контексте моего комментария ниже про то, что BinaryFormatter устарел, всё верно он ругается на него, а значит эта строчка не нужна.

2024-02-27 14:25 UTC, KitovDanil commented on ConsoleApp4/Program.cs
> +    public class TextFile
Класс TextFile, являющийся, по сути, originator'ом из паттерна Memento, не имплементирует интерфейс IOriginator, хотя в нем есть методы CreateMemento() и RestoreMemento(), аналогичные методам интерфейса. При этом сам memento как участник паттерна присутствует в виде класса TextFileMemento, а вот caretaker отсутствует вовсе, поскольку даже ссылок на методы CreateMemento() и RestoreMemento() в программе 0. Я делаю вывод, что работа с паттерном проведена не до конца.

2024-02-27 14:25 UTC, KitovDanil commented on ConsoleApp4/Program.cs
> +        public static DocumentManager GetInstance()
Видно, что была идея в том, что DocumentManager - это Singleton, а значит стоит создать его instance и получать методом GetInstance(). Идея верная, вот только ссылок на метод GetInstance() в коде 0. Вместо этого в методе Main() класса Application создается новый объект DocumentManager, у которого вызывается метод ChooseDocument(). Методы у Singleton вызываются не так, а вот так:
```
public class Singleton
{
    public static Singleton Instance
    {
        get
        {
            if (instance == null) instance = new Singleton();
            return instance;
        }
    }
    public void Method1() { Console.WriteLine("Singleton.Method1"); }
    public void Method2() { Console.WriteLine("Singleton.Method2"); }
    private Singleton() { }
    private static Singleton instance;
}
class Program
{
    static void Main(string[] args)
    {
        Singleton.Instance.Method1();
        Singleton.Instance.Method2();
    }
}
```
Предлагаю либо убрать использование Singleton, либо переписать вызовы его методов нормальным образом.

2024-03-01 01:45 UTC, StasLina commented on ConsoleApp4/Program.cs
> +    public string fileName { get; set; }
Учтено.

2024-03-01 01:45 UTC, StasLina commented on ConsoleApp4/Program.cs
> +        Dictionary<int, string> curKeywords = new Dictionary<int, string>();
учтено.

2024-03-01 01:45 UTC, StasLina commented on ConsoleApp4/Program.cs
> +            return;
убрано.

2024-03-01 01:45 UTC, StasLina commented on ConsoleApp4/Program.cs
> +        Dictionary<int, TextFile> listFiles = new Dictionary<int, TextFile>();
убрано

2024-03-01 02:19 UTC, StasLina commented on ConsoleApp4/Program.cs
> +            backupContent = new TextFileMemento(this.fileContent);
использую this для более наглядно обращение к элементам, + появляется удобная подсказка

2024-03-01 02:19 UTC, StasLina commented on ConsoleApp4/Program.cs
> +            Console.WriteLine("Введите имя для нового файа, который будет бинарно серелизован");
исправил

2024-03-01 02:20 UTC, StasLina commented on ConsoleApp4/Program.cs
> +using System.Diagnostics;
Убрал

2024-03-01 02:20 UTC, StasLina commented on ConsoleApp4/Program.cs
> +    public class TextFile
Реализовал класс CareTaker который является смотрителем за Memento,
Реализовал интерфейс IOriginator с методами GetMemento SetMeneto

2024-03-01 02:20 UTC, StasLina commented on ConsoleApp4/Program.cs
> +        public static DocumentManager GetInstance()
Убрал

2024-03-01 06:36 UTC, KitovDanil requested changes

2024-03-01 06:36 UTC, KitovDanil commented on ConsoleApp4/Program.cs
> +                KeyValuePair<int, List<string>> AtElment = curDictionary.ElementAt(this.elementIndexCategory);
Локальная переменная в PascalCase. В некоторых методах этого же класса такая же проблема.

2024-03-01 06:36 UTC, KitovDanil commented on ConsoleApp4/Program.cs
> +        public TextFileSearcher(string DirectoryPath)
Аргумент метода в PascalCase.

2024-03-01 06:36 UTC, KitovDanil commented on ConsoleApp4/Program.cs
> +            string FileContent = File.ReadAllText(filePath);
Локальная переменная в PascalCase.

2024-03-01 06:36 UTC, KitovDanil commented on ConsoleApp4/Program.cs
> +        private Dictionary<int, object> AssClassMemento = new Dictionary<int, object>();
![image](https://github.com/StasLina/PRGR/assets/8685613/7696203a-aeca-4f6d-8f14-8d2d4678358c)

2024-03-01 06:36 UTC, KitovDanil commented on ConsoleApp4/Program.cs
> +        public void SerializeBinary(string FileName)
Ряд методов с аргументом в PascalCase.

2024-03-01 06:36 UTC, KitovDanil commented on ConsoleApp4/Program.cs
> +            "6. Интерфэйс серилизации\\десерилизации\n";
Слово "интерфейс" устоялось в языке и пишется через "е": https://ru.wiktionary.org/wiki/%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D1%84%D0%B5%D0%B9%D1%81
Аналогично со словом "сериализация". Пишется через 'а' - "сериАлизация": https://ru.wiktionary.org/wiki/%D1%81%D0%B5%D1%80%D0%B8%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F
Выше в методах путаница: где-то написано правильно Serialize, где-то неправильно Serilization. То же применимо и к десериализации.

2024-03-01 06:36 UTC, KitovDanil commented on ConsoleApp4/Program.cs
> +            "Текстовый команды редактора:\n" +
"Текстовый" в множественном числе надо

2024-03-01 06:36 UTC, KitovDanil commented on ConsoleApp4/Program.cs
> +            Console.WriteLine("Текущая дирректория: {0}", fileDirectory);
Директория

2024-03-01 06:36 UTC, KitovDanil commented on ConsoleApp4/Program.cs
> +                    Console.WriteLine("Продолжить? Enter - продолжить");
Думаю, имеет смысл написать, какой есть альтернативный вариант типа: "Нажмите Enter, чтобы продолжить, или любую другую клавишу, чтобы закончить"

2024-03-01 06:36 UTC, KitovDanil commented on ConsoleApp4/Program.cs
> +            Console.WriteLine("Введите файловую дирректорию для индексации");
Директорию

2024-03-01 07:03 UTC, StasLina commented on ConsoleApp4/Program.cs
> +#pragma warning disable SYSLIB0011
Если удалить строчку с #pragma warning disable SYSLIB0011  то неиспользуемые функции SerializeBinaryOld и DeserializeBinaryOld но показывающие функциональность перестанут компилироваться.

2024-03-01 07:05 UTC, StasLina commented on ConsoleApp4/Program.cs
> +            string FileContent = File.ReadAllText(filePath);
учтено

2024-03-01 07:05 UTC, StasLina commented on ConsoleApp4/Program.cs
> +        public TextFileSearcher(string DirectoryPath)
учтено

2024-03-01 07:05 UTC, StasLina commented on ConsoleApp4/Program.cs
> +                KeyValuePair<int, List<string>> AtElment = curDictionary.ElementAt(this.elementIndexCategory);
Учтено

2024-03-01 07:06 UTC, StasLina commented on ConsoleApp4/Program.cs
> +        public void SerializeBinary(string FileName)
учтено

2024-03-01 07:07 UTC, StasLina commented on ConsoleApp4/Program.cs
> +            "Текстовый команды редактора:\n" +
учтено

2024-03-01 07:07 UTC, StasLina commented on ConsoleApp4/Program.cs
> +            Console.WriteLine("Текущая дирректория: {0}", fileDirectory);
учтено

2024-03-01 07:13 UTC, StasLina commented on ConsoleApp4/Program.cs
> +        private Dictionary<int, object> AssClassMemento = new Dictionary<int, object>();
AssClassMemento слово ass расширяется как association

2024-03-01 07:56 UTC, KitovDanil approved these changes

2024-03-01 07:57 UTC, merged