06 delegates events develop
StasLina/PRGR pull request #9
Opened 2024-03-21 06:11 UTC by StasLina

2024-03-21 13:26 UTC, KitovDanil requested changes

2024-03-21 13:26 UTC, KitovDanil commented on ConsoleApp3/Program.cs
> +        CreateMatrix(out Matr1);
Бурмин же забанил out и ref

2024-03-21 13:26 UTC, KitovDanil commented on ConsoleApp3/Program.cs
> +        for (int i = 0; i < rowCount; i++)
Однобуквенные индексы

2024-03-21 13:26 UTC, KitovDanil commented on ConsoleApp3/Program.cs
> +    public enum TypeHhandleEvents
Лишняя h в названии

2024-03-21 13:26 UTC, KitovDanil commented on ConsoleApp3/Program.cs
> +    private CalculationDelegate calculationDelegate;
Переменная нигде не используется. Вместо неё активно используется listHandle.

2024-03-21 13:35 UTC, StasLina commented on ConsoleApp3/Program.cs
> +        CreateMatrix(out Matr1);
Они необходимы для работы

2024-03-22 01:14 UTC, StasLina commented on ConsoleApp3/Program.cs
> +        for (int i = 0; i < rowCount; i++)
Уничетожены

2024-03-22 01:15 UTC, StasLina commented on ConsoleApp3/Program.cs
> +    public enum TypeHhandleEvents
уничтожено

2024-03-22 01:15 UTC, StasLina commented on ConsoleApp3/Program.cs
> +    private CalculationDelegate calculationDelegate;
уничтожена

2024-03-22 04:47 UTC, merged